###register
Post http://localhost:3000/auth/register
Content-Type: application/json

{
    "username":"sadeghims",
    "email":"sadeghism@yahoo.com",
    "mobile":"09902875296",
    "password":"123456789",
    "confirm_password":"123456789"
}

###login
Post http://localhost:3000/auth/login
Content-Type: application/json
Authorization: {{$dotenv SECRET_KEY}}

{
    "username":"sadeghims",
    "password":"123456789"
}